server:
    http2:
        enabled: true

spring:
    datasource:
        url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/NotsBlock
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:example}
        hikari:
            pool-name: NotsBlock
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            jdbc:
                time_zone: America/Bogota
            ddl-auto: update
        open-in-view: false
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    jta:
        enabled: false

springdoc:
    show-actuator: true

management:
    endpoint:
        health:
            show-details: ALWAYS
            probes:
                enabled: true

    endpoints:
        web:
        exposure:
        include: "*"